---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  # - name: instance
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
  - name: molecule-ubi8-init-1
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    workingDir: '/tmp'
  # - name: molecule-ubi9
  #   image: registry.access.redhat.com/ubi9/ubi-init:latest
  #   workingDir: '/tmp'
