---
- name: Demo playbook
  hosts: "{{ nodes | default('localhost') }}"
  vars:
    system_report_path: '/tmp/reports'
  tasks:
    # - ansible.builtin.include_role:
    #   name: system-report
    - name: Set generation timestamp
      set_fact:
        date_time_text: "{{ lookup('pipe','date -d \"now + 8 hours\" +%Y-%m-%d_%H-%M-%S') | string }}"

    - name: Template with report
      ansible.builtin.template:
        src: system-report.html
        dest: "{{ system_report_path }}/{{ ansible_hostname }}.html"
        force: true
      delegate_to: localhost
